### PR TITLE
modified the readme to suit the backend idea

### PR DESCRIPTION
**Pull request by Petsamuel**
- modified readme 
- added the contribution.md file

### CODE REVIEW

**Comment by DevoAbhi** [comment]
That's great work!
Can you also mention steps to setup the repo:
1) after cloning -> npm install
2) npm run start to start the server

**Comment by DevoAbhi** [comment]
Hey just noticed. 
I am not using MongoDB in this. I am not storing any info in this app.

**Comment by Petsamuel** [comment]
> Hey just noticed. I am not using MongoDB in this. I am not storing any info in this app.

would fix that

**Comment by DevoAbhi** [comment]
Great work!
LGTM

**Pull request merged**
